# Generated by Django 3.2.3 on 2021-06-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
